pipeline {
  agent any
  stages {
    stage("build") {
      steps {
        sh 'docker build -t nandeeshreddy/myapp:latest -f project9/Dockerfile project9/'
      }
    }
    stage("push") {
      steps {
          withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
            sh '''
                echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                docker push nandeeshreddy/myapp:latest
            '''
          }
       }
     }
    stage("Deploy") {
      steps {
        sh '''
        ssh user@server "docker pull nandeeshreddy/myapp:latest && \
        docker stop myapp || true && \
        docker rm myapp || true && \
        docker run -d -p 80:5000 --name myapp nandeeshreddy/myapp:latest"
        '''
      }
    }
  }
}
